# Generated by Django 5.0.1 on 2026-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='tempuser', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
