# Generated by Django 5.0.1 on 2026-02-01 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField()),
                ('model_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='openai', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('spec_building', 'Building Intent Spec'), ('validating', 'Validating'), ('planning', 'Building Component Plan'), ('graph_building', 'Building Dependency Graph'), ('folder_contracts', 'Generating Folder Contracts'), ('code_generation', 'Generating Code'), ('assembling', 'Assembling Repository'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('zip_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('repo_directory', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=50)),
                ('complexity', models.CharField(choices=[('minimal', 'Minimal'), ('standard', 'Standard'), ('full', 'Full')], default='minimal', max_length=20)),
                ('stack', models.JSONField(default=dict)),
                ('features', models.JSONField(default=list)),
                ('architecture', models.JSONField(default=dict)),
                ('data_entities', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent_spec', to='projects.project')),
            ],
            options={
                'verbose_name': 'Intent Specification',
                'verbose_name_plural': 'Intent Specifications',
            },
        ),
        migrations.CreateModel(
            name='FolderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=100)),
                ('folder_path', models.CharField(max_length=500)),
                ('files', models.JSONField(default=list)),
                ('imports', models.JSONField(default=list)),
                ('interfaces', models.JSONField(default=list)),
                ('models_used', models.JSONField(default=list)),
                ('generated_code', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_contracts', to='projects.project')),
            ],
            options={
                'verbose_name': 'Folder Contract',
                'verbose_name_plural': 'Folder Contracts',
            },
        ),
        migrations.CreateModel(
            name='DependencyGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('build_order', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_graph', to='projects.project')),
            ],
            options={
                'verbose_name': 'Dependency Graph',
                'verbose_name_plural': 'Dependency Graphs',
            },
        ),
        migrations.CreateModel(
            name='ComponentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component_plan', to='projects.project')),
            ],
            options={
                'verbose_name': 'Component Plan',
                'verbose_name_plural': 'Component Plans',
            },
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='projects_pr_user_id_3cbd31_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foldercontract',
            unique_together={('project', 'component_id')},
        ),
    ]
