# Generated by Django 5.0.1 on 2026-03-05 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField()),
                ('model_provider', models.CharField(choices=[('gemini', 'Google Gemini')], default='gemini', max_length=20)),
                ('gemini_model', models.CharField(choices=[('gemini-3-pro-preview', 'Gemini 3 Pro'), ('gemini-3-flash-preview', 'Gemini 3 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default='gemini-2.5-flash', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('spec_building', 'Building Intent Spec'), ('review_required', 'Review Required'), ('validating', 'Validating'), ('planning', 'Building Component Plan'), ('code_generation', 'Generating Code'), ('assembling', 'Assembling Repository'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('spec_confirmed', models.BooleanField(default=False)),
                ('zip_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('repo_directory', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('gemini_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.apikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Pipeline Action Log',
                'verbose_name_plural': 'Pipeline Action Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100)),
                ('stack', models.JSONField(default=dict)),
                ('api_type', models.CharField(choices=[('rest', 'REST'), ('graphql', 'GraphQL'), ('none', 'None')], default='rest', max_length=20)),
                ('features', models.JSONField(default=list)),
                ('architecture', models.CharField(choices=[('monolith', 'Monolith'), ('microservices', 'Microservices')], default='microservices', max_length=20)),
                ('data_entities', models.JSONField(default=list)),
                ('auth_method', models.CharField(choices=[('jwt', 'JWT'), ('session', 'Session'), ('none', 'None')], default='none', max_length=20)),
                ('vague_intent', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent_spec', to='projects.project')),
            ],
            options={
                'verbose_name': 'Intent Specification',
                'verbose_name_plural': 'Intent Specifications',
            },
        ),
        migrations.CreateModel(
            name='ComponentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component_plan', to='projects.project')),
            ],
            options={
                'verbose_name': 'Component Plan',
                'verbose_name_plural': 'Component Plans',
            },
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='projects_pr_user_id_3cbd31_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
    ]
