# Generated by Django 5.0.1 on 2026-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentspec',
            name='creative_vision',
            field=models.TextField(blank=True, default=''),
        ),
    ]
