# Generated by Django 5.0.1 on 2026-02-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_model_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash (Recommended)'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default='gemini-2.5-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='model_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini')], default='gemini', max_length=20),
        ),
    ]
