# Generated by Django 5.0.1 on 2026-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_gemini_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foldercontract',
            old_name='imports',
            new_name='dependencies',
        ),
        migrations.AddField(
            model_name='foldercontract',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
    ]
