# Generated by Django 5.0.1 on 2026-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_imports_foldercontract_dependencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentspec',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intentspec',
            name='vague_intent',
            field=models.BooleanField(default=False),
        ),
    ]
