# Generated by Django 5.0.1 on 2026-02-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_intentspec_explanation_intentspec_vague_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spec_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('spec_building', 'Building Intent Spec'), ('review_required', 'Review Required'), ('validating', 'Validating'), ('planning', 'Building Component Plan'), ('graph_building', 'Building Dependency Graph'), ('folder_contracts', 'Generating Folder Contracts'), ('code_generation', 'Generating Code'), ('assembling', 'Assembling Repository'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
