# Generated by Django 5.0.1 on 2026-02-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apikey'),
        ('projects', '0006_project_spec_confirmed_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gemini_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.apikey'),
        ),
    ]
