# Generated by Django 5.0.1 on 2026-02-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_gemini_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-3-pro-preview', 'Gemini 3 Pro'), ('gemini-3-flash-preview', 'Gemini 3 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default='gemini-2.5-flash', max_length=50),
        ),
        migrations.CreateModel(
            name='PipelineActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Pipeline Action Log',
                'verbose_name_plural': 'Pipeline Action Logs',
                'ordering': ['created_at'],
            },
        ),
    ]
